services:
  redlib:
    build:
      context: .
      args:
        BUILDKIT_INLINE_CACHE: "0"
        CARGO_PROFILE: "release"
        CARGO_PROFILE_DIR: "release"
        USE_SCCACHE: "1"
        GIT_HASH: "${GIT_HASH:-dev}"
    restart: always
    container_name: "redlib"
    user: nobody
    read_only: true
    ports:
      - 8080:8080 
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    env_file: .env
    volumes:
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    environment:
      REDLIB_DEV_FS_CSS: "1"
      REDLIB_DEV_NOCACHE: "1"
      IPV4_ONLY: "1"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  redlib:
